name: Compile Java Exercises
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile Java files
        run: |
          mkdir -p out
          javac -d out $(find src -name "*.java")

      - name: Run Main class
        run: |
          java -cp out com.duggavamshidhar.Main
